#include <string.h>
#include <stdio.h>

#include "hal_data.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
	fsp_err_t err;

	// Message buffer
	char msg[50];

	// Initialize UART (channel 8)
	err = R_SCI_B_UART_Open(&g_uart8_ctrl, &g_uart8_cfg);
	if (FSP_SUCCESS != err)
	{
		while(1);
	}

	// Main loop
	uint32_t count = 0;
    while(1)
    {
    	// Write counter to serial terminal
    	sprintf(msg, "Count: %u\r\n", count);
		R_SCI_B_UART_Write(&g_uart8_ctrl, (uint8_t*)msg, strlen(msg));
		count++;

    	// Turn LED on
        R_BSP_PinAccessEnable();
        R_BSP_PinWrite(BSP_IO_PORT_06_PIN_00, BSP_IO_LEVEL_HIGH);
        R_BSP_PinAccessDisable();

        // Wait 500 ms
        R_BSP_SoftwareDelay(500, BSP_DELAY_UNITS_MILLISECONDS);

        // Turn LED off
        R_BSP_PinAccessEnable();
        R_BSP_PinWrite(BSP_IO_PORT_06_PIN_00, BSP_IO_LEVEL_LOW);
        R_BSP_PinAccessDisable();

        // Wait 500 ms
        R_BSP_SoftwareDelay(500, BSP_DELAY_UNITS_MILLISECONDS);
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED

        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif
    }
}
