#include <string.h>
#include <stdio.h>

#include "hal_data.h"

/******************************************************************************
 * main() is generated by the RA Configuration editor and is used to generate
 * threads if an RTOS is used. This function is called by main() when no RTOS
 * is used.
 *****************************************************************************/
void hal_entry(void)
{
    fsp_err_t err;
    char msg[50];

    /* Initialize UART (channel 8) */
    err = R_SCI_B_UART_Open(&g_uart8_ctrl, &g_uart8_cfg);
    if (FSP_SUCCESS != err)
    {
        while(1);
    }

    /* Main loop */
    uint32_t count = 0;
    while(1)
    {
        /* Write counter to serial terminal */
        sprintf(msg, "Count: %u\r\n", count);
        R_SCI_B_UART_Write(&g_uart8_ctrl, (uint8_t*)msg, strlen(msg));
        count++;

        /* Turn LED on */
        R_BSP_PinAccessEnable();
        R_BSP_PinWrite(BSP_IO_PORT_06_PIN_00, BSP_IO_LEVEL_HIGH);
        R_BSP_PinAccessDisable();

        /* Wait 500 ms */
        R_BSP_SoftwareDelay(500, BSP_DELAY_UNITS_MILLISECONDS);

        /* Turn LED off */
        R_BSP_PinAccessEnable();
        R_BSP_PinWrite(BSP_IO_PORT_06_PIN_00, BSP_IO_LEVEL_LOW);
        R_BSP_PinAccessDisable();

        /* Wait 500 ms */
        R_BSP_SoftwareDelay(500, BSP_DELAY_UNITS_MILLISECONDS);
    }
}
